services:
  mysql8.0:
    image: mysql:8.0
    container_name: mysql80
    restart: always
    privileged: true
    ports:
      - "3306:3306"
    volumes:
      - "./servers/mysql/mysql8.0/config:/etc/mysql"  # 配置文件
      - "./data/mysql/mysql8.0:/var/lib/mysql"        # 数据库文件
      - "./logs/mysql/mysql8.0:/var/log/mysql"        # 日志文件
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD_80}"
      - "MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST_80}"
      - "MYSQL_USER=${MYSQL_USER_80}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD_80}"
    networks:
      - dnmp

  redis6.2:
    image: redis:6.2
    container_name: redis62
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./servers/redis/redis6.2/config:/etc/redis"  # 配置文件
      - "./data/redis/redis6.2:/data"                 # 数据文件
      - "./logs/redis/redis6.2:/var/log/redis"        # 日志文件
    environment:
      - "TZ=${TZ}"
    entrypoint: ["redis-server", "/etc/redis/docker.conf", "--requirepass", "${REDIS_PASSWORD_62}"]
    networks:
      - dnmp

  php74:
    build:
      context: ./servers/php/php7.4
      dockerfile: Dockerfile
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS_74: ${PHP_EXTENSIONS_74}
        COMPOSER_IMAGE_URL: ${COMPOSER_IMAGE_URL}
        COMPOSER_DOWNLOAD_URL: ${COMPOSER_DOWNLOAD_URL}
        TZ: ${TZ}
      #platform: linux/amd64  # 强制使用amd64架构构建
    container_name: php74
    restart: always
    ports:
      - "9002:9000"
    volumes:
      - "./servers/php/php7.4/config/php.ini:/usr/local/etc/php/php.ini:ro"                   # php.ini
      - "./servers/php/php7.4/config/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw"             # php-fpm.conf
      - "./servers/php/php7.4/config/php-fpm.d:/usr/local/etc/php-fpm.d"                      # php-fpm.d
      - "./servers/php/php7.4/config/supervisor/supervisord.conf:/etc/supervisord.conf:ro"    # supervisor配置文件
      - "./logs/php/php7.4:/var/log/php"                                                      # 日志文件
      - "./panel:/usr/panel"                                                                  # nginx使用unix连接文件
      - "${PROJECT_DIRECTORY}:/usr/share/nginx/html"                                                  # 站点文件路径
    cap_add:
      - SYS_PTRACE
    networks:
      - dnmp

  php82:
    build:
      context: ./servers/php/php8.2
      dockerfile: Dockerfile
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS_82: ${PHP_EXTENSIONS_82}
        COMPOSER_IMAGE_URL: ${COMPOSER_IMAGE_URL}
        COMPOSER_DOWNLOAD_URL: ${COMPOSER_DOWNLOAD_URL}
        TZ: ${TZ}
    container_name: php82
    restart: always
    ports:
      - "9005:9000"
    volumes:
      - "./servers/php/php8.2/config/php.ini:/usr/local/etc/php/php.ini:ro"                   # php.ini
      - "./servers/php/php8.2/config/php-fpm.conf:/usr/local/etc/php-fpm.conf:rw"             # php-fpm.conf
      - "./servers/php/php8.2/config/php-fpm.d:/usr/local/etc/php-fpm.d"                      # php-fpm.d
      - "./servers/php/php8.2/config/supervisor/supervisord.conf:/etc/supervisord.conf:ro"    # supervisor配置文件
      - "./logs/php/php8.2:/var/log/php"                                                      # 日志文件
      - "./panel:/usr/panel"                                                                  # nginx使用unix连接文件
      - "${PROJECT_DIRECTORY}:/usr/share/nginx/html"                                                  # 站点文件路径
    cap_add:
      - SYS_PTRACE
    networks:
      - dnmp

  nginx1.28:
    build:
      context: ./servers/nginx/nginx1.28
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        NGINX_REGISTER_ACME_MAIL: ${NGINX_REGISTER_ACME_MAIL_1_28}
    container_name: nginx1.28
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./servers/nginx/nginx1.28/config:/etc/nginx"   # 配置文件
      - "./logs/nginx/nginx1.28:/var/log/nginx"         # 日志文件
      - "./panel:/usr/panel"                            # php unix连接文件
      - "${PROJECT_DIRECTORY}:/usr/share/nginx/html"    # 站点文件路径
    environment:
      - "SSL_DOMAINS=${NGINX_SSL_DOMAINS_1_28}"
      - "SSL_SERVER=${NGINX_SSL_SERVER_1_28}"
      - "SSL_DNS=${NGINX_SSL_DNS_1_28}"
      - "SSL_BASE_DIR=${NGINX_SSL_BASE_DIR_1_28}"
      - "RELOAD_CMD=${NGINX_RELOAD_CMD_1_28}"
    networks:
      - dnmp

  node22:
    build:
      context: ./servers/node/node22
      dockerfile: Dockerfile
      args:
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        TZ: ${TZ}
    container_name: node22
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - "${PROJECT_DIRECTORY}:/www"    # 站点文件路径
    stdin_open: true
    tty: true
    networks:
      - dnmp

networks:
  dnmp:
    name: dnmp
    driver: bridge