name: Build Docker image

on:
  workflow_dispatch: # 手动触发工作流程
  pull_request:
    branches:
      - main  # 在拉取请求合并到 main 分支时触发
  schedule:
    - cron: '0 0 * * 1' # 每周一 0点（UTC），相当于中国时间每周一凌晨8点
#  push:
#    branches:
#      - main  # 在推送到 main 分支时触发

jobs:
  build_php_images:
    strategy:
      fail-fast: false  # 让所有任务运行完成，失败不会中断其他任务
      matrix:
        php_version:
          - php72
          - php73
          - php74
          - php80
          - php81
          - php82
          - php83
          - php84  # 分别测试不同的 PHP 版本
    runs-on: ubuntu-latest
    name: Build and Test ${{ matrix.php_version }} Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 设置 Buildx 环境

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # 设置 QEMU 以支持多架构

      - name: Load .env file
        run: |
          if [ -f .github/workflows/.env ]; then
            # 只导出符合格式的环境变量
            grep -v '^#' .github/workflows/.env | grep '=' | while IFS= read -r line; do
              # 忽略以 '=' 开头的行和空行
              if [[ "$line" =~ ^[^=]+=.+$ ]]; then
                export "$line"
              fi
            done
          fi
        shell: /usr/bin/bash -e {0}  # 加载 .env 文件，导出符合格式的环境变量

      - name: Build Docker image for ${{ matrix.php_version }}
        run: docker compose -f compose.sample.yml --env-file .github/workflows/.env build ${{ matrix.php_version }}
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Verify ${{ matrix.php_version }} Docker image
        run: |
          docker compose -f compose.sample.yml --env-file .github/workflows/.env up -d ${{ matrix.php_version }}
          docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.php_version }} php -v  # 验证 PHP 版本
          docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.php_version }} php -m  # 验证 PHP 扩展

  build_service_images:
    strategy:
      fail-fast: false
      matrix:
        service:
          - nginx1.21
          - redis6.2
          - mysql5.7
          - mysql8.0
          - node22
          - rabbitmq3.11
          - mongo6.0
    runs-on: ubuntu-latest
    name: Build and Test ${{ matrix.service }} Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Load .env file
        run: |
          if [ -f .github/workflows/.env ]; then
            # 只导出符合格式的环境变量
            grep -v '^#' .github/workflows/.env | grep '=' | while IFS= read -r line; do
              # 忽略以 '=' 开头的行和空行
              if [[ "$line" =~ ^[^=]+=.+$ ]]; then
                export "$line"
              fi
            done
          fi
        shell: /usr/bin/bash -e {0}  # 加载 .env 文件，导出符合格式的环境变量

      - name: Build Docker image for ${{ matrix.service }}
        run: docker compose -f compose.sample.yml --env-file .github/workflows/.env build ${{ matrix.service }}
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Verify ${{ matrix.service }} Docker image
        run: |
          docker compose -f compose.sample.yml --env-file .github/workflows/.env up -d ${{ matrix.service }}
          # 根据服务类型执行相应的验证步骤
          if [ "${{ matrix.service }}" = "nginx1.21" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} nginx -v
          elif [ "${{ matrix.service }}" = "redis6.2" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} redis-server --version
          elif [ "${{ matrix.service }}" = "mysql5.7" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} mysql --version
          elif [ "${{ matrix.service }}" = "mysql8.0" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} mysql --version
          elif [ "${{ matrix.service }}" = "node22" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} node -v
          elif [ "${{ matrix.service }}" = "rabbitmq3.11" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} rabbitmqctl status | grep "RabbitMQ version"
          elif [ "${{ matrix.service }}" = "mongo6.0" ]; then
            docker compose -f compose.sample.yml --env-file .github/workflows/.env exec ${{ matrix.service }} mongod --version
          fi