name: Build Docker image

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 在拉取请求合并到 main 分支时触发

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Load .env file
        run: |
          if [ -f .github/workflows/.env ]; then
            # 只导出符合格式的环境变量
            grep -v '^#' .github/workflows/.env | grep '=' | while IFS= read -r line; do
              # 忽略以 '=' 开头的行和空行
              if [[ "$line" =~ ^[^=]+=.+$ ]]; then
                export "$line"
              fi
            done
          fi
        shell: /usr/bin/bash -e {0}

      - name: Build Docker images with .env
        run: docker compose -f .github/workflows/compose.yml --env-file .github/workflows/.env build
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Verify Docker image with .env
        run: |
          docker compose -f .github/workflows/compose.yml --env-file .github/workflows/.env up -d
          for php_version in php72 php73 php74 php80 php81 php82 php83; do
            docker compose -f .github/workflows/compose.yml exec -T $php_version php -v # 验证 PHP 版本
            docker compose -f .github/workflows/compose.yml exec -T $php_version php -m # 验证 PHP 扩展
          done
          
      - name: Tear down
        if: always()
        run: |
          docker compose -f .github/workflows/compose.yml down
          docker image prune -af # 删除所有未被使用的 Docker 镜像。
          docker volume prune -f # 删除所有未被使用的 Docker 数据卷。
          docker system prune -af # 删除所有未被使用的 Docker 容器、网络和缓存数据。