name: Build Docker PHP image

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发
  pull_request:
    branches:
      - main  # 在拉取请求合并到 main 分支时触发
  schedule:
    - cron: '0 0 * * 1' # 每周一0点开始

jobs:
  build_docker_images:
    strategy:
      fail-fast: false  # 让所有任务运行完成，失败不会中断其他任务
      matrix:
        php_version:
          - php72
          - php73
          - php74
          - php80
          - php81
          - php82
          - php83  # 分别测试不同的 PHP 版本
    runs-on: ubuntu-latest
    name: Build and Test ${{ matrix.php_version }} Docker Image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 设置 Buildx 环境

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # 设置 QEMU 以支持多架构

      - name: Load .env file
        uses: direnv/direnv-action@v1
        with:
          env-file: .github/workflows/.env

      - name: Build Docker image for ${{ matrix.php_version }}
        run: docker compose -f compose.sample.yml --env-file .github/workflows/.env build ${{ matrix.php_version }}
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1

      - name: Verify ${{ matrix.php_version }} Docker image
        run: |
          docker compose -f compose.sample.yml --env-file .github/workflows/.env up -d ${{ matrix.php_version }}
          docker compose -f compose.sample.yml exec -T ${{ matrix.php_version }} php -v  # 验证 PHP 版本
          docker compose -f compose.sample.yml exec -T ${{ matrix.php_version }} php -m  # 验证 PHP 扩展

cleanup:
  runs-on: ubuntu-latest
  needs: build  # 等待所有 build 任务完成
  if: always()  # 确保清理任务在所有任务完成后执行
  steps:
    - name: Cleanup Docker resources
      run: |
        docker compose -f compose.sample.yml down  # 停止并删除所有由 Docker Compose 管理的容器、网络和卷
        docker image prune -af  # 清理未使用的 Docker 镜像
        docker volume prune -f  # 清理未使用的 Docker 数据卷
        docker system prune -af  # 清理未使用的 Docker 容器、网络和缓存数据